services:

  #User service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    working_dir: /var/app/users

  #Nginx Service
  nginx:
    image: nginx
    container_name: 'nginx-server'
    volumes:
      - ./var/log/nginx:/var/log/nginx #log файлы.
      - ./volumes/etc/nginx/nginx.conf:/etc/nginx/nginx.conf:ro #Конфигурация nginx.
    ports:
      - "80:80"
      - "443:443"
    restart: unless-stopped

  #PostgreSQL Service
  user_db:
    image: postgres
    container_name: 'Postgre-server'
    volumes: 
      - user_db:/var/lib/postgresql/data/
    ports:
        - "5432:5432"
    restart: unless-stopped
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
